### ISSUE TITLE
Config reference

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/api.silverstripe.org#10]
This is a bit more of a starting point of the conversation we'd like to have for "how do we document config?". At the moment the configuration system is a critical feature of the silverstripe framework API, and the actual configurable options lack any real formal documentation.

My suggestion would be to leverage the `@config` phpdoc identifier to build a list of configurable elements.

For instance, if I go to http://api.silverstripe.org/3.1/class-Director.html I would probably benefit from a "list of configurable options" section.

**Comment by dhensby** [comment]
I guess some feedback on this would be good, hey?

Yes, I think that having a list of config options on each API doc would be very useful and we should be encouraging (if not enforcing) `@config` PHPdoc on all Config vars.

Although, perhaps that *forces* people to use `private statics` to declare configs - is this something that we want to continue in the long term?

**Comment by chillu** [comment]
I think the problem is a bit wider than that: You need to know which class or namespace to look for in the first place. A key like `allowed_extensions` is fairly self explanatory, but its fairly arbitrarily placed in `File` rather than `Filesystem` or `Upload`. So I think a global list would be more useful than a class-specific one (as a starting point). Looks like APIGen only [supports](https://github.com/ApiGen/ApiGen/wiki/supported-annotations) a narrow set of annotations, so would need some investigation.

As a sidenote, I found this blog entry from the PHP-DI project really interesting in how they handle config: http://php-di.org/news/06-php-di-4-0-new-definitions.html. Make more sense in a DI context than a generic configuration framework like ours, but nevertheless interesting to see how they use PHP's syntax to make it more readable.

**Comment by sminnee** [comment]
Does the move to Sami make this easier?

**Comment by tractorcow** [comment]
Not sure; Still needs to be investigated.

**Comment by robbieaverill** [comment]
@dhensby has resolved this in #75
