### ISSUE TITLE
Developer documention API needs a rewrite to handle a) unreleased versions, and b) namespacing

### ISSUE THREAD

**Issue by mspacemedia** [silverstripe/api.silverstripe.org#32]
https://docs.silverstripe.org/en/4/developer_guides/extending/extensions/

Link for DataExtension at foot of page links to:

http://api.silverstripe.org/search/lookup/?q=DataExtension&version=4&module=framework&_ga=1.176688039.308834275.1455201581

Which errors with:

Not Found

The requested URL /4/class-DataExtension.html was not found on this server.

**Comment by robbieaverill** [comment]
Thanks @mspacemedia! To do this the framework requires a 4 branch, which will be created when the 4.x code is ready for beta release. Until then I think we will just put up with it.

**Comment by robbieaverill** [comment]
There's a couple of things going on here:

* The core modules need a `4` branch to work with the redirection from the docs site
* The docs should otherwise be updated to redirect `4` to `master` in API site links
* The docs themselves need to reference the fully qualified class names here, not just `DataExtension`, e.g.`\SilverStripe\ORM\DataExtension`. The API docs are available under the correct namespace already, e.g. http://api.silverstripe.org/master/class-SilverStripe.ORM.DataExtension.html

**Comment by SpiritLevel** [comment]
@robbieaverill . http://api.silverstripe.org/master/class-SilverStripe.ORM.DataExtension.html doesn't seem be working...replacing **master** with **3.5** or **3.6** doesn't get it working either....

**Comment by robbieaverill** [comment]
I think a solution for this is that `/search/lookup.php` needs to examine all the combined `.upgrade.yml` mapping files and perform a dynamic rewrite of `DataExtension` to `SilverStripe\ORM\DataExtension`. This would save the whole "rewrite half of the docs". In places where an unqualified class name exists in two namespaces the docs could use the FQCN explicitly.
