### ISSUE TITLE
Searching for a class that is a suffix of another class, where the class you want comes alphabetically after the longer version, brings up unwanted results

### ISSUE THREAD

**Issue by ss23** [silverstripe/api.silverstripe.org#5]
Trying to bring up the documentation for `TimeClass`, will instead search for anything with `TimeClass`, meaning that `DateTimeClass` will come up first. In the case where the thing you're searching for is a _prefix_ you can simply append a `::`, however, this is not possible when it's a suffix that I'm aware of.

Expect results would probably be either a special identifier to signify start of the class name (think a regex style `^TimeClass`, or mix and match the results from any search to not be alphabetical (that is, when you search for `TimeClass`, display a mix of results from both `DateTimeClass` and `TimeClass`, giving you a better chance of finding the results you will find helpful.

**Comment by sminnee** [comment]
@tractorcow is this still an issue on your Sami version?

**Comment by sminnee** [comment]
Checking the UAT server (search for "DataObject" and GraphQL results come first, and "Field" returns "GridField" first), it looks like it is.

One fix would be to do the following priority order:

 * exact-match on a symbol (classname, or methodname)
 * startswith-match on a symbol
 * any-match on a symbol

**Comment by dhensby** [comment]
Fix at #77 

I did a slightly different priority order. I don't treat method names as their own symbol because it really pollutes the search results when you search `Field` do you really want all the matches for `*Field::Field` to come before a list of classes ending in `Field`?

I prioritise as follows after splitting at namespace separator and working right to left (classname to root namespace)

- exact match
- starts with
- ends with
- any-match
