### ISSUE TITLE
4.x API - docs inconsistent with current release

### ISSUE THREAD

**Issue by DorsetDigital** [silverstripe/api.silverstripe.org#70]
The API docs seem to be showing an inconsistency in the versions of released code.

eg.
If you install the current Silverstripe stable (4.0.3) as per the instructions, you'll get v1.0.3 of silverstripe/asset-admin

The 4.x API docs are currently showing code from what looks like the v1.1 branch (possibly this is also the master).  There are differences in the methods / properties between the two branches, so you end up with the documentation being misleading compared to the stable release.

If you install the 4.1.0-rc2 branch of Silverstripe, you get the higher version of asset-admin which matches the API docs

As the 4.1 branch comes online, and runs in parallel with the 4.0 branch, there will presumably be more occurrences of this as the various dependencies may diverge between the two. 

Should the documentation be further broken down to 4.0.x and 4.1.x to avoid this happening in the future?

**Comment by robbieaverill** [comment]
Yeah the docs we pull in are just for the major version, similar to how docs.silverstripe.org works now.

I'm not sure to be honest what the best approach to document new APIs between minor versions is, short of literally labelling everything new that gets added with "(SS 4.2 and newer only)" for example.

**Comment by dhensby** [comment]
The docs are for the most recent minor feature sets at the moment; we can't really have docs that fail to disclose functionality

**Comment by dhensby** [comment]
Hmmm - I guess that could be confusing, but we don't really have a way to split the docs by stable/unstable at the moment. I'm not sure this is so much a "bug" either way as we build docs off of the current 4.x branch which means this would be an expected side-effect of doing so.

**Comment by andrewandante** [comment]
This has just been raised again, in relation to MySQL SSL Support - it is present in the docs: https://docs.silverstripe.org/en/3/getting_started/installation/how_to/mysql_ssl_support/ but is absent from a stable 3 release. This is _as bad as_ 
> docs that fail to disclose functionality
as it is docs that advertise non-existent functionality, or at least unreachable.

Can we at least pin to the latest stable tag, or something like that? Going off the branch raw is asking for trouble.

For example, 3.6.0 was tagged in May. Anything committed to the 3 branch since then is in the 3 docs, but not available in a stable 3 release. This _doesn't make sense_.
